image:
  registry: "ghcr.io"
  repository: "yevhenko/kbot"
  pullPolicy: IfNotPresent
  tag: "v1.3.0-9950e33"
  os: ""
  arch: ""
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
