image:
  registry: "ghcr.io"
  repository: "yevhenko/kbot"
  pullPolicy: IfNotPresent
  tag: "v1.3.0-887864e"
  os: "linux"
  arch: "amd64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
