name: KBOT-CICD

on: 
  push:
    branches:
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Login to GitHub Container Registry'
        run: echo "${{ secrets.BOT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build&Push
        env:
          APP: "kbot"
        run: make image push

